import type { GraphicQuality, GraphicProfile } from '../types';

export const GRAPHIC_PROFILES: Record<GraphicQuality, GraphicProfile> = {
  fast: {
    id: 'fast',
    label: 'Fast',
    subtitle: 'Mobile Real-Time Speed',
    badge: 'MOBILE',
    recommendedFor: 'Mobile smartphones, battery-saving mode, or low-end hardware',
    fpsTarget: 'Maximum Framerate',
    dpr: [0.75, 1.0],
    shadows: false,
    shadowMapSize: 512,
    waterSegments: 80,
    waveCount: 2,
    waterShader: {
      capillaryDist: 50,
      capillaryHarmonics: 1,
      sssDist: 45,
      foamDist: 50,
      wakesEnabled: false,
      glitterEnabled: false,
      horizonLODCutoff: 500,
    },
    atmosphereParticles: 30,
    fogDensityDay: 0.0014,
    fogDensityNight: 0.0016,
    fogNear: 70,
    fogFar: 320,
    maxViewDistance: 380,
    islandDetailDistance: 80,
    toneMappingExposureDay: 1.05,
    toneMappingExposureNight: 1.10,
  },
  balanced: {
    id: 'balanced',
    label: 'Balanced',
    subtitle: 'Standard Web Experience (1080p Cap)',
    badge: 'DEFAULT',
    recommendedFor: 'Laptops, general desktop browsers & mid-range PCs',
    fpsTarget: '60 FPS (Max 1080p)',
    dpr: [1.0, 1.25],
    maxResolution: { width: 1920, height: 1080 },
    shadows: true,
    shadowMapSize: 1024,
    waterSegments: 140,
    waveCount: 4,
    waterShader: {
      capillaryDist: 140,
      capillaryHarmonics: 3,
      sssDist: 160,
      foamDist: 140,
      wakesEnabled: true,
      glitterEnabled: true,
      horizonLODCutoff: 800,
    },
    atmosphereParticles: 120,
    fogDensityDay: 0.0011,
    fogDensityNight: 0.0012,
    fogNear: 140,
    fogFar: 480,
    maxViewDistance: 560,
    islandDetailDistance: 140,
    toneMappingExposureDay: 1.08,
    toneMappingExposureNight: 1.12,
  },
  performance: {
    id: 'performance',
    label: 'Performance',
    subtitle: 'Ultra Photorealism AAA',
    badge: 'ULTRA REALISM',
    recommendedFor: 'Gaming PCs, Apple Silicon Retina Macs & high-end GPUs',
    fpsTarget: 'Cinematic Visual Fidelity',
    dpr: [1.5, 2.5],
    shadows: true,
    shadowMapSize: 1024,
    waterSegments: 140,
    waveCount: 6,
    waterShader: {
      capillaryDist: 160,
      capillaryHarmonics: 5,
      sssDist: 180,
      foamDist: 160,
      wakesEnabled: true,
      glitterEnabled: true,
      horizonLODCutoff: 900,
    },
    atmosphereParticles: 180,
    fogDensityDay: 0.00090,
    fogDensityNight: 0.0010,
    fogNear: 180,
    fogFar: 620,
    maxViewDistance: 750,
    islandDetailDistance: 220,
    toneMappingExposureDay: 1.10,
    toneMappingExposureNight: 1.15,
  },
};

export const GRAPHIC_QUALITY_LIST: GraphicQuality[] = ['fast', 'balanced', 'performance'];

