import type { GraphicQuality, GraphicProfile } from '../types';

export const GRAPHIC_PROFILES: Record<GraphicQuality, GraphicProfile> = {
  fast: {
    id: 'fast',
    label: 'Fast',
    subtitle: 'Mobile Real-Time Speed',
    badge: 'MOBILE',
    recommendedFor: 'Mobile smartphones, battery-saving mode, or low-end hardware',
    fpsTarget: 'Maximum Framerate',
    dpr: [0.75, 1.0],
    shadows: false,
    shadowMapSize: 512,
    waterSegments: 90,
    waveCount: 2,
    waterShader: {
      capillaryDist: 70,
      capillaryHarmonics: 1,
      sssDist: 60,
      foamDist: 70,
      wakesEnabled: false,
      glitterEnabled: false,
      horizonLODCutoff: 650,
    },
    atmosphereParticles: 40,
    fogDensityDay: 0.0013,
    fogDensityNight: 0.0015,
    fogNear: 80,
    fogFar: 360,
    maxViewDistance: 450,
    islandDetailDistance: 90,
    toneMappingExposureDay: 1.25,
    toneMappingExposureNight: 1.22,
  },
  balanced: {
    id: 'balanced',
    label: 'Balanced',
    subtitle: 'Standard Web Experience',
    badge: 'DEFAULT',
    recommendedFor: 'Laptops, general desktop browsers & mid-range PCs',
    fpsTarget: '60 FPS Balanced',
    dpr: [1.0, 1.5],
    shadows: true,
    shadowMapSize: 1024,
    waterSegments: 160,
    waveCount: 4,
    waterShader: {
      capillaryDist: 180,
      capillaryHarmonics: 3,
      sssDist: 200,
      foamDist: 180,
      wakesEnabled: true,
      glitterEnabled: true,
      horizonLODCutoff: 950,
    },
    atmosphereParticles: 180,
    fogDensityDay: 0.0010,
    fogDensityNight: 0.0011,
    fogNear: 160,
    fogFar: 550,
    maxViewDistance: 650,
    islandDetailDistance: 160,
    toneMappingExposureDay: 1.28,
    toneMappingExposureNight: 1.24,
  },
  performance: {
    id: 'performance',
    label: 'Performance',
    subtitle: 'Ultra Photorealism AAA',
    badge: 'ULTRA REALISM',
    recommendedFor: 'Gaming PCs, Apple Silicon Retina Macs & high-end GPUs',
    fpsTarget: 'Cinematic Visual Fidelity',
    dpr: [1.25, 1.85],
    shadows: true,
    shadowMapSize: 2048,
    waterSegments: 180,
    waveCount: 8,
    waterShader: {
      capillaryDist: 240,
      capillaryHarmonics: 5,
      sssDist: 240,
      foamDist: 220,
      wakesEnabled: true,
      glitterEnabled: true,
      horizonLODCutoff: 1200,
    },
    atmosphereParticles: 260,
    fogDensityDay: 0.00085,
    fogDensityNight: 0.00095,
    fogNear: 220,
    fogFar: 750,
    maxViewDistance: 900,
    islandDetailDistance: 280,
    toneMappingExposureDay: 1.32,
    toneMappingExposureNight: 1.28,
  },
};

export const GRAPHIC_QUALITY_LIST: GraphicQuality[] = ['fast', 'balanced', 'performance'];
